### ISSUE TITLE
Improve wait for status in container package

### ISSUE THREAD

**Issue by NicolasMahe** [mesg-foundation/engine#1159]
The function `DockerContainer.waitForStatus` should be improved to wait a few seconds that the tasks and the container doesn't contain any error and are running properly.

Currently, if tasks doesn't contain any error and the container has the right status, the function return immediately.
This system catch the error during the creation of the container but doesn't catch errors that occurs when the container start (eg: the app of the container exit).

Docker's cli is waiting 5 seconds after the creation of a service to make sure everything started correctly :
```
overall progress: 1 out of 1 tasks 
1/1: running   [==================================================>] 
verify: Service converged
```

We could implement a similar system.

**Comment by ilgooz** [comment]
Since Docker cannot know about internals of services and cannot dictate their implementations, it doesn't have any other option other than waiting for a fixed amount of time like 5 secs and assume that services are running.

On the other hand mesg already knows about the services. It defines the protocol about each services should listen for incoming executions on start, emit results and events.

I think we can safely assume that, if a service starts to listen for tasks, it already did the necessary preparation like initializing some code, opening files from FS, connecting to the database, checking status of 3rd party APIs and so on. A proper service should do all kind of initializations like this and then start listening for executions.

After service started to listen executions, I think Engine should assume that service did everything that it needs to do on startup and haven't failed. Which indicates that service is up and ready. 

I think Engine should implement this check system in the `Instance.Create()` API. _Create_ API should start the instance as it already do but wait for service to listen for executions before returning.

If a service doesn't start for listening executions after doing all other setup, it can be considered as a "low quality" service.

**Comment by antho1404** [comment]
we now use containers directly from the CLI https://github.com/mesg-foundation/js-sdk/pull/199
