### ISSUE TITLE
Generate 10 validators and 10 cosmos account in genesis

### ISSUE THREAD

**Issue by NicolasMahe** [mesg-foundation/engine#1385]
Generate 10 validators and 10 cosmos account with tokens in the genesis instead of just 1.

**Comment by NicolasMahe** [comment]
Debrief of the pair programming session:
- can create multiple validator in one transaction with multiple message. all validators need to sign the tx
- 2/3 of the validator needs to be connected to each other in order to start the blockchain

So, pre-seeding the genesis with validators that are not running is not an option.

So here a small todo for this issue:
- [ ] group the 3 scripts into a new one.
  - it should accept as parameters the necessary info and also the number of validator to generate
  - generate the accounts with nice name and generated password (like docker container name)
  - output the private info (account password, mnemonic)
  - output in a way that is easily parsing by another script (could be JSON, until YAML-based config file)
- [ ] simplify dev. remove unused envs and variables
  - still copy the keybase and the validator identity when needed (using command flags)
- [ ] remove unused `Config.Comsos.ValidatorPubKey` (check if other config can be removed)
- [ ] update `node.createAppState` to be compatible with multiple accounts (multiple signers)

**Comment by krhubert** [comment]
The draft https://github.com/mesg-foundation/engine/pull/1386 contains everything expects running multiple hosts without modifying the dev file. I've tried to find a way to do so, but the only solution is to use config and generate different config for each host. Otherwise processing env variables with different prefixes is not an option.

So for me now we should either run them by hand or switch to yaml. If you find a nice solution to manage a multi-dimensional array of envs in bash please share.

**Comment by NicolasMahe** [comment]
> * [ ]  output in a way that is easily parsing by another script (could be JSON, until YAML-based config file)

Instead of outputting stuff in the console, the script in PR https://github.com/mesg-foundation/engine/pull/1391 is writing files. Like this the script is called only once and the files can be read multiple times.
