### ISSUE TITLE
Split Execution to ExecutionRequest and ExecutionResult

### ISSUE THREAD

**Issue by NicolasMahe** [mesg-foundation/engine#1542]
Split the Execution resource to ExecutionRequest and ExecutionResult.
New sdk, new api.
This is a breaking change and need update to the js-sdk.

Also the name ExecutionRequest and ExecutionResult should be simplified.

**Comment by NicolasMahe** [comment]
@antho1404 @krhubert what name do you suggest?
After some conversation with Antho, we were ok to use the shortest and simpler name even if it doesn't give all the context. The execution is the core of the MESG project, so it should be fine.

If we also integrate the future consensus on the creation of the execution and the validation of the result, then we have 4 different words to find:
- The execution instruction itself (instance hash, task key, inputs, list of executor, list of verifiers/validators)
- The output of the execution (outputs, executor address)
- The list of node that run the process and witness that an execution should be created and executed. First consensus.
- The verification or validation of the execution's result. The list of node that verify/validate or reject the outputs of the execution against its inputs. Second and last consensus.

My suggestion is:
- Emitter, Execution, Result, Verification

**Comment by antho1404** [comment]
I'm 100% ok with `Emitter, Execution, Result, Verification`. Simple and efficient. I'm not sure tho that `Emitter` is needed as it could be part of the execution itself but that's another subject

**Comment by krhubert** [comment]
In my opinion, they are too simple. I prefer to use more explicit names - in that case maybe with a prefix.  It gives us:

- explicitness - eg. `Result` can be result of execution, but also a process (in the future) or any other result. Same with `Verification` - it can be execution Verification as well as block Verification

My proposal is:

- `Exeuction` as we have right now (but also we have a `Task`, which is kind of Execution but external one, but it's different subject to join them)
- `Execution Result` - results of execution
- `Exeuction Validators` - validator execution nodes 
- `Exeuction Emitter` - this one is tricky because for me `Emitter` is someone who creates the execution and this leads us to 
- `Execution Workers` - list of nodes that actually runs the executions

The same scenario we can have with event's - `Emitter`, `Workers` or even with `Process` (although I like the `Workflow` name and I'm not sure why we changed it) - `Process Workers`, etc...

My point is that given names are too generic and could be applied to many things.

Regardless of the decisions, I think it might be good time to **introduce a Glossary** a put every definition we have and we plan to use. 

A glossary would be useful for user (docs) but also for ourselves, so naming would be clear and might help us to introduce good naming in the future

**Comment by NicolasMahe** [comment]
closing this issue as it has been implemented by simply add a `emitters` list to execution: https://github.com/mesg-foundation/engine/pull/1705
