### ISSUE TITLE
Benchmark/performances for the executions

### ISSUE THREAD

**Issue by antho1404** [mesg-foundation/engine#1570]
When trying to fix https://github.com/mesg-foundation/engine/issues/1537 I realized that with the current configuration we were only capable of processing 4-5 transactions per block.

This can come from 2 problems:
- we reach the block capacity, either with the size of the messages (which I doubt) or the number of gas spent (more likely)
- the processing/validation before adding in the pool of transaction takes a lot of time and we can only sign/broadcast ~4 transactions per seconds (current block time)

We have a huge bottleneck somewhere, I think because we try to send the transactions in a synchronous way. I have high doubts that this is just because of pure processing like hashing functions or so but it might be something to explore too.

---

I tried to increase the block time to 10 seconds and it seems that we can process about 20-25 transactions (with similar executions message) so it seems that the problem doesn't come from the capacity of the block.

**Comment by antho1404** [comment]
I run a bunch of tests to try to understand the bottleneck issue that we have

## Tests

Run the process of this repository https://github.com/antho1404/application-erc20-analytics
You can monitor the metrics with this branch/PR https://github.com/mesg-foundation/engine/pull/1580

## Results

We always the same kind of results
- Execution created and pre-signed immediately
- Execution signed with a delay (blue curve)
- Execution in progress connected to tx signed until a certain point where it stops
- Execution completed caped by the executions in progress

It seems that there is a correlation between the transaction signed (blue) and the transaction completed (red) but that doesn’t impact the transaction in progress

The signature/broadcast of the transaction is clearly a bottleneck that needs to be fixed

<img width="1751" alt="Screen Shot 2020-01-03 at 21 17 08" src="https://user-images.githubusercontent.com/1783126/71728019-90de7600-2e6e-11ea-8cd1-97f2bd6ddd31.png">

**Comment by NicolasMahe** [comment]
Source code that should be the source of the problem for the slowness of signing / broadcasting:
https://github.com/mesg-foundation/engine/blob/47b743ef849f840cd77a4b345bae2d14721d48cb/cosmos/client.go#L84-L128
- TODO: implement the mutex in a much more clever way

Extracting the account and signature logic to a dedicated structure can only help. Started in PR https://github.com/mesg-foundation/engine/pull/1573 because of issue https://github.com/mesg-foundation/engine/issues/1565

Two attempts to create benchmark on the whole API:
- https://github.com/mesg-foundation/engine/pull/1621
- https://github.com/mesg-foundation/engine/pull/1622
