### ISSUE TITLE
Required field for hash calculation of a service

### ISSUE THREAD

**Issue by antho1404** [mesg-foundation/engine#1709]
Now that we entirely control the hash calculation of a service it might be interesting to re-think what is actually needed for the hash calculation. A service is composed of definitions (configuration, task arguments etc...) and documentation (descriptions, name etc...)

## Keep the current hash

The current hash takes all the data definitions and descriptions and hash them together.
It's easy but any change in the documentation will change the hash without changing the behavior of the service (not sure it's something good)

## Definition fields only

We could base the hash only on the data that change the behavior of the service (tasks, events, dependencies, source...). This means that any update in the documentation will not change the current hash. It also means that to change a service hash you will need to add/remove a definition, making it slightly harder to duplicate a service.

## Source 

Every service has a source that points to an IPFS hash that contains the tarball of the service. This might but sufficient enough for the hash calculation as this IPFS hash will contain all definitions and documentation as well so any changes in that will result in a different IPFS hash.

_Originally posted by @antho1404 in https://github.com/mesg-foundation/engine/pull/1692_

**Comment by NicolasMahe** [comment]
I like the idea of hashing only the "Definition fields only".
The current hash is calculated from so many values that it doesn't really represent what the service does.
I don't like to use only the source as the service's tarball contains also the `mesg.yml` and the dependencies versioning from a package manager.

The issue with "definition fields only" is it will restrict publishing a service after its documentation has been fixed for example. But maybe this issue is related to a service upgrade system and not to the hash itself?.
