### ISSUE TITLE
Issue with service deploy after start

### ISSUE THREAD

**Issue by Roms1383** [mesg-foundation/engine#990]
If chaining `service deploy` after `start` like so : 
>$ mesg-core stop; mesg-core start; mesg-core service deploy

Even with a long sleep like so : 
>$ mesg-core stop; mesg-core start; sleep 10; mesg-core service deploy

It invariably ends up with an error.

---

On the other hand, even if launched one after another like so : 
>$ mesg-core stop; mesg-core start
>$ mesg-core service deploy

It works like a charm.

---

As opposed, for example, with chaining `service validate` after `start` like so : 
>$ mesg-core stop; mesg-core start; mesg-core service validate

Which works like a charm.

---

Here's a screenshot attesting :

<img width="719" alt="Screen Shot 2562-05-28 at 23 50 18" src="https://user-images.githubusercontent.com/21016014/58497470-3b3e3e80-81a6-11e9-8d6c-7e503858fea7.png">

---

This is annoying since it prevents to fully automate multiple commands like in Continous Integration pipeline, or `package.json`'s `scripts`, etc.

**Comment by ilgooz** [comment]
Hi, thank you for your feedback!

`service validate` command does not need reach to Engine daemon to validate a service. So, that's why you aren't getting any errors in your command chain while using it.

As you already pointed out, start command does not wait for Core daemon to accept connections. This behavior may change in future and we may add some flags to utilize this.

For now, you can use a bash command to check if Core is ready to accept connections in your automation script with something like below:

```bash
while ! nc -z 127.0.0.1 50052; do  # Engine listens at 50052.
  sleep 1 # wait and try checking availability after 1 sec.
done

mesg-core start
mesg-core service deploy [SERVICE]
```

If this doesn't work for you please add your further questions in this issue: https://github.com/mesg-foundation/engine/issues/911
